### ISSUE TITLE
QUE SE CAYE PORFAVOR

### ISSUE THREAD

**Issue by antonicarol** [royalmo/TripleBot#2]
MANITO ETE BOT E MU CHARLATAN,

BANEA SU USO A SPEKTRIBBYYYYYYYYYY

**Comment by royalmo** [comment]
Abans del 2022 estarà implementat :)

**Comment by royalmo** [comment]
Tens propostes de com posar limits? Del pal havia pensat que la gent nomes pogues un audio per minut, i que ames a mes hi hagues un limit de 4 per cada 10 minuts i 15 per cada hora, idk

**Comment by antonicarol** [comment]
Es podría posar un CoolDown a nivell de usuari, per evitar spam.

En si el que comentes ya esta be, limitar a 4 comandes per 5-10 minuts.

**Comment by royalmo** [comment]
Obviament posare que si la id de usuari coincideix amb la meva que no m'apliqui el cooldown xDD

**Comment by antonicarol** [comment]
Em sembla perfecte, s'han de tenir clares les preferéncies.

Y sobretot al SPECTRIBBY cooldown de 120 minuts.

**Comment by royalmo** [comment]
![817e576bd6d9f9e48e8b55b7c922d894](https://user-images.githubusercontent.com/49844173/104091391-6d1def00-527d-11eb-9fc3-45aef6a269b0.jpg)

**Comment by BinarySandia04** [comment]
Estic d'acord la veritat














`Eric fes algo programa`
